### ISSUE TITLE
Notifications no longer coming in

### ISSUE THREAD

**Issue by antifuchs** [jnordberg/irccloudapp#19]
It seems irccloud changed the structure of their notifications, causing Nimbus to no longer show pop-ups when highlight words are mentioned. I haven't debugged this further, just thought it would be useful to have an issue for this.

**Comment by nesl247** [comment]
Any update on this? It would be really nice to have this working again.

**Comment by bemjb** [comment]
I haven't had any time to work on Nimbus recently, and I havenat heard of anyone else working on it. I'd be more than happy to review and integrate pull requests, though!

**Comment by jnordberg** [comment]
Works for me, let me know if the latest version doesn't show notifications for you
