### ISSUE TITLE
Feature request: show unread message count in dock icon a la Adium

### ISSUE THREAD

**Issue by jbellis** [jnordberg/irccloudapp#20]
![screen shot 2014-09-17 at 2 11 06 pm](https://cloud.githubusercontent.com/assets/42158/4309655/b3ef88de-3e9e-11e4-95c5-ff3cb0685ab7.png)

**Comment by Hidendra** [comment]
It seems to already do this for highlights.

... though given this issue is so old, maybe it was added since then.

**Comment by jnordberg** [comment]
It has been doing it from the beginning :)
