### ISSUE TITLE
Cannot upload images

### ISSUE THREAD

**Issue by cmluciano** [jnordberg/irccloudapp#23]
For some reason I cannot upload images like I can in the web interface. When I click the "upload a file option" nothing happens. The other buttons under the "up" arrow all seem to function as designed. My only guess is that I don't have permissions set up correctly?

**Comment by cmluciano** [comment]
Ah, this might be related #22

**Comment by bemjb** [comment]
Yeah, I need to merge #22 and put out a new release. Unfortunately, I haven't had time in the last couple of weeks, but I'll get it in no later than next week. Apologies for the delay.
