### ISSUE TITLE
Upload a file option does not work

### ISSUE THREAD

**Issue by jisuo** [jnordberg/irccloudapp#24]
The latest feature to the right of the chat input box has a "Upload a file" option. It does not work in Nimbus, but it does work in the browser (Safari). The other 3 options does work though.

**Comment by bemjb** [comment]
What version of Nimbus do you have? You should try downloading the latest version that's on the site, as automatic updates are not working right now. If that still doesn't work, can you describe the steps you are taking to upload a file and what is happening when you do that?

**Comment by jisuo** [comment]
I have the latest: Version 0.7.4 (12)

I click on the arrow, and select "Upload a file..." and then nothing happens. That's it.

**Comment by bemjb** [comment]
Does dragging and dropping the file on the window work?

I'm not in front of my computer right now, so I can't test it, but I'm curious what @Dahlgren thinks since he implemented the file upload support.

**Comment by jisuo** [comment]
No I tried to drag the image to both the chat area and to the input box, but nothing happens there either. Works on Safari though, as I mentioned earlier.

**Comment by Dahlgren** [comment]
It's only available since the 0.7.5 (13) release with my upload fix, see https://github.com/jnordberg/irccloudapp/releases/tag/0.7.5-prerelease. Both the upload form triggered from the message field and drag n drop is working properly with that version, I just tried it by downloading from the release.

**Comment by jisuo** [comment]
Thanks, it works on that version. I had only tried the auto updater so this explains why it didn't work.

**Comment by Dahlgren** [comment]
Great! I guess this issue can be closed then :)

**Comment by jisuo** [comment]
Closing!
