### ISSUE TITLE
leaks my client usage to third parties

### ISSUE THREAD

**Issue by sneak** [jnordberg/irccloudapp#33]
Predictably, as a web wrapper, Nimbus makes all of the same 3p connections that irccloud.com does, including ones to Google and Facebook:

<img width="592" alt="Screen Shot 2020-09-25 at 15 09 52" src="https://user-images.githubusercontent.com/408977/94320911-06c9c680-ff43-11ea-9d07-77db06c910c5.png">
<img width="560" alt="Screen Shot 2020-09-25 at 15 10 00" src="https://user-images.githubusercontent.com/408977/94320914-092c2080-ff43-11ea-8426-6dd6a4074e5b.png">
<img width="593" alt="Screen Shot 2020-09-25 at 15 10 19" src="https://user-images.githubusercontent.com/408977/94320916-09c4b700-ff43-11ea-9ed3-076889360c45.png">
<img width="627" alt="Screen Shot 2020-09-25 at 15 10 23" src="https://user-images.githubusercontent.com/408977/94320917-0a5d4d80-ff43-11ea-9930-ee0f13711607.png">

I don't expect desktop client software to do this, generally, so I wanted to report this as a violation of the principle of least surprise.  I've no experience with Electron; is it possible to bundle these dependencies into the client app so these requests aren't made?

**Comment by jnordberg** [comment]
Not really, the app is just webkit view that loads irccloud.com. You could try to integrate more deeply with irccloud.com and try to be smart what to load and keep local copies of dependencies like you suggest but that will be a nightmare to maintain considering it could break every time they change something. Less effort to write a native app using their APIs at that point
